name: LifeStealSouls
main: com.snoxier.lifesteal.LifeStealPlugin
version: 1.0.0
api-version: '1.20'
authors: ["snoxie", "snoxier"]
description: Lifesteal for ashfall.
commands:
  lsmax:
    description: Set maximum hearts (global or per player)
    usage: /<command> <maxHearts> [player]
    permission: lifesteal.admin
  withdraw:
    description: Withdraw hearts into physical items, leaving at all times at least one.
    usage: /<command> <amount>
    permission: lifesteal.withdraw
  permissions:
   lifesteal.admin:
    default: op
  lifesteal.withdraw:
    default: true
    