name: LogBook
main: gg.snox.logbook.LogBook
version: 1.0.0
api-version: '1.21'
authors: [ "snoxier" ]
commands:
  log:
    description: Manage and view punishments
    usage: /log <add|view|ban|mute|kick>
    aliases: [logs, logbook]
permissions:
  logbook.admin:
    description: Allows managing viewers and viewing any player's logs
    default: op
  logbook.punish:
    description: Allows using /log ban|mute|kick
    default: op
  logbook.view:
    description: Allows /log view if added via /log add
    default: true
